cafe/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('orders/', include('orders.urls'))
]

orders/urls.py
from django.urls import path

from orders.views import (
    create,
    delete_order,
    edit_order,
    get_404,
    orders,
    list_order,
    search,
    shift,
    status_change
)

app_name = 'orders'
urlpatterns = [
    path('', shift, name='shift'),
    path('create/', create, name='create'),
    path('<int:pk>/', orders, name='order'),
    path('<int:pk>/edit/', edit_order, name='edit_order'),
    path('<int:pk>/status/', status_change, name='status_change'),
    path('<int:pk>/delete/', delete_order, name='delete_order'),
    path('list/', list_order, name='list'),
    path('search/', search, name='search'),
    path('get_404/', get_404, name='get_404')
]

orders/models.py
from django.db import models

from core.constants import STATUS


class Dish(models.Model):
    name = models.CharField(max_length=256, verbose_name='Название блюда')
    price = models.IntegerField(verbose_name='Цена')

    def __str__(self):
        return f'{self.name} цена {self.price}'


class Order(models.Model):
    table_number = models.SmallIntegerField(verbose_name='Номер стола')
    items = models.ManyToManyField(Dish, verbose_name='Блюда')
    total_price = models.IntegerField(verbose_name='Цена')
    status = models.PositiveSmallIntegerField(
        choices=STATUS,
        verbose_name='Статус заказа',
        default=1
    )

    class Meta:
        default_related_name = 'order'


class Shift(models.Model):
    is_open = models.BooleanField(default=True)
    orders = models.ManyToManyField(Order, verbose_name='Заказы')

    class Meta:
        default_related_name = 'shift'

    def str(self):
        return self.id

orders/forms.py
from django import forms
from django.core.exceptions import ValidationError

from orders.models import Order


class OrderCreateForm(forms.ModelForm):

    class Meta:
        model = Order
        fields = ('table_number', 'items')
        widgets = {
            'items': forms.CheckboxSelectMultiple
        }

    def clean_table_number(self):
        table_number = self.cleaned_data.get('table_number')

        if table_number is not None and table_number < 0:
            raise ValidationError('Номера стола не может быть отрицательным.')

        return table_number

orders/views.py
from django.shortcuts import redirect, render

from core.constants import STATUS
from orders.forms import OrderCreateForm
from orders.models import Order, Shift


def shift(request):
    template_name = 'orders/shift.html'
    message = None
    shifts = Shift.objects.all().order_by('-id')
    current_shift = shifts.filter(is_open=True).last()
    if request.method == 'POST':
        if 'open' in request.POST:
            try:
                Shift.objects.get(is_open=True)
                message = 'Смена уже открыта'
            except Shift.DoesNotExist:
                Shift.objects.create()
                message = 'Смена открыта'
        elif 'close' in request.POST:
            try:
                shift = Shift.objects.get(is_open=True)
                shift.is_open = False
                shift.save()
                message = 'Смена закрыта'
            except Shift.DoesNotExist:
                message = 'Нет открытой смены'
    elif request.method == 'GET':
        if 'calculate' in request.GET:
            try:
                shift_id = request.GET.get('shift_id')
                shift = Shift.objects.get(pk=shift_id)
                orders = Order.objects.filter(shift=shift)
                earnings = sum(order.total_price for order in orders)
                message = f'Выручка {earnings}'
            except Shift.DoesNotExist:
                message = 'Такой смены нет'
            except ValueError:
                message = 'Номер смены не задан'

    context = {
        'shifts': shifts,
        'message': message,
        'current_shift': current_shift
    }
    return render(request, template_name, context)


def search(request):
    template_name = 'orders/search.html'
    order_id = request.GET.get('order_id')
    message = None
    if order_id:
        try:
            Order.objects.get(pk=order_id)
            return redirect('orders:order', pk=order_id)
        except Order.DoesNotExist:
            message = f'Заказ c ID {order_id} не найден.'
        except ValueError:
            message = 'Некорректно задан номер стола'

    context = {'message': message}
    return render(request, template_name, context)


def list_order(request):
    template_name = 'orders/list.html'
    orders = Order.objects.all().order_by('-id')
    message = None
    query = request.GET.get('search', '')
    status_filter = request.GET.get('status', '')

    if query:
        try:
            if int(query) > 0:
                print(type(query))
                orders = orders.filter(table_number=query)
            else:
                message = 'Некорректно задан номер стола'
        except ValueError:
            message = 'Некорректно задан номер стола'

    if status_filter:
        if status_filter in [str(st[0]) for st in STATUS]:
            orders = orders.filter(status=status_filter)
        else:
            message = 'Некорректно задан статус'

    context = {
        'orders': orders,
        'search_query': query,
        'statuses': STATUS,
        'selected_status': status_filter,
        'message': message}
    return render(request, template_name, context)


def create(request):
    template_name = 'orders/form.html'

    shift = Shift.objects.get_or_create(is_open=True)

    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            total_price = sum(dish.price for dish in form.cleaned_data['items'])
            order.total_price = total_price
            form.save()
            shift[0].orders.add(order)
            return redirect('orders:order', pk=order.id)
    else:
        form = OrderCreateForm()

    context = {'form': form}
    return render(request, template_name, context)


def orders(request, pk):
    template_name = 'orders/order.html'
    try:
        order = Order.objects.get(pk=pk)
        context = {'order': order}
        return render(request, template_name, context)
    except Order.DoesNotExist:
        return redirect('orders:get_404')


def edit_order(request, pk):
    template_name = 'orders/form.html'
    try:
        order = Order.objects.get(pk=pk)
        if order.status == 3:
            return redirect('orders:order', pk=pk)
        if request.method == 'POST':
            form = OrderCreateForm(request.POST, instance=order)
            if form.is_valid():
                total_price = sum(
                    dish.price for dish in form.cleaned_data['items']
                )
                order.total_price = total_price
                form.save()
                return redirect('orders:order', pk=pk)
        else:
            form = OrderCreateForm(instance=order)
            context = {'form': form}
            return render(request, template_name, context)
    except Order.DoesNotExist:
        return redirect('orders:get_404')


def status_change(request, pk):
    try:
        order = Order.objects.get(pk=pk)
        if order.status < 3:
            order.status += 1
        order.save()
        return redirect('orders:order', pk=pk)
    except Order.DoesNotExist:
        return redirect('orders:get_404')


def delete_order(request, pk):
    try:
        order = Order.objects.get(pk=pk)
        order.delete()
    except Order.DoesNotExist:
        return redirect('orders:get_404')
    return redirect('orders:list')


def get_404(request):
    template = 'orders/get_404.html'
    return render(request, template)

templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Кафе</title>
    
    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'css/stylesheet.css' %}">
</head>
<body>
    <div class="container pt-5">
        <p>
            <a href="{% url 'orders:shift' %}" class="button button-blue">Смена</a>
            <a href="{% url 'orders:create' %}" class="button button-blue">Создать заказ</a>
            <a href="{% url 'orders:list' %}" class="button button-blue">Все заказы</a>
            <a href="{% url 'orders:search' %}" class="button button-blue">Найти заказ</a>
        </p>
    </div>
    <div class="container pt-5">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

templates/orders/form.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'css/stylesheet.css' %}">

<div class="card">
    <div class="card-header">
        <h3>Сделать заказ</h3>
    </div>
    <div class="card-body">
        <form method="post" novalidate>
            {% csrf_token %}
            
            <div class="form-group">
                <label for="{{ form.table_number.id_for_label }}">Номер стола</label>
                {{ form.table_number}}
                {% if form.table_number.errors %}
                    <div class="alert-warning">
                        {{ form.table_number.errors }}
                    </div>
                {% endif %}
            </div>

            <div class="form-group">
                <label for="{{ form.items.id_for_label }}">Выберите блюда</label>
                {{ form.items }}
                {% if form.items.errors %}
                    <div class="alert-warning">
                        {{ form.items.errors }}
                    </div>
                {% endif %}
            </div>

            <button type="submit" class="button button-blue">Посчитать</button>
        </form>
    </div>
</div>
{% endblock %}

templates/orders/get_404.html
{% extends "base.html" %}

{% load django_bootstrap5 %}

{% block content %}
<div class="card col-4">
  <div class="card-header">
    <h3>Заказ c не найден</h3>
  </div>
  <div class="card-body">
  </div>
</div>
{% endblock %}

templates/orders/list.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'css/stylesheet.css' %}">
<div class="card">
  <div class="card-header">
    <h3>Список заказов</h3>
    <form method="GET" action="">
      <label for="search">Поиск по номеру стола:</label>
      <input type="number" id="search" name="search" placeholder="Поиск по номеру стола" value="{{ search_query }}" min="1">
      {% if message %}
        <div class="alert-warning">
            {{ message }}
        </div>
      {% endif %}
      <label for="status">Статус:</label>
      <select id="status" name="status" class="select">
        <option value="">Все заказы</option>
        {% for status in statuses %}
          <option value="{{ status.0 }}" {% if selected_status == status.0|stringformat:"s" %}selected{% endif %}>{{ status.1 }}</option>
        {% endfor %}
      </select>
      <button type="submit" class="button button-blue">Поиск</button>
    </form>
  </div>
  <div class="card-body">
    {% if orders %}
      {% for order in orders %}
          <div class="order">
            <div class="order-header">Заказ ID: {{ order.id }}</div>
            <div>Номер стола: {{ order.table_number }}</div>
            <div>Список блюд:
              <ul class="item-list">
                  {% for dish in order.items.all %}
                    <li>{{ dish.name }} ({{ dish.price }})</li>
                  {% endfor %}
              </ul>
            </div>
            <div>Общая стоимость: {{ order.total_price }}</div>
            <div>Статус: {{ order.get_status_display }}</div>
            <p>
              <a href="{% url 'orders:order' order.id %}" class="button button-green">Редактировать</a>
            </p>
          </div>
      {% endfor %}
    {% else %}
      <p>Нет заказов для отображения.</p>
    {% endif %}
  </div>
</div>
{% endblock %}

templates/orders/order.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'css/stylesheet.css' %}">
<div class="card">
    <div class="card-header">
        <h3>Заказ номер {{ order.id }}</h3>
    </div>
  
    <div class="card-body">
        <div class="order">Номер стола {{ order.table_number }}</div>
        <div>Список блюд:
            <ul class="item-list">
                {% for dish in order.items.all %}
                    <li>{{ dish.name }} цена {{ dish.price }}</li>
                {% endfor %}
            </ul>
        </div>
        <div>Общая стоимость: {{ order.total_price }}</div>
        <div>Статус: {{ order.get_status_display }}
            <a href="{% url 'orders:status_change' order.id %}" class="button button-blue">Изменить статус</a>
        </div>
    
        <p>
            <a href="{% url 'orders:edit_order' order.id %}" class="button button-green">Редактировать</a>
            <a href="{% url 'orders:delete_order' order.id %}" class="button button-red">Удалить заказ</a>
        </p>
    </div>
</div>
{% endblock %}

templates/orders/search.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'css/stylesheet.css' %}">
<div class="card">
  <div class="card-header">
    <h3>Найти заказ</h3>
  </div>
  <div class="card-body">
    <form method="get">
      <label for="order_id">Введите ID заказа:</label>
      <input type="number" min="1" id="order_id" name="order_id" required>
      <button type="submit" class="button button-blue">Найти</button>
    </form>
    {% if message %}
      <p>{{ message }}</p>
    {% endif %}
  </div>
</div>
{% endblock %}

templates/orders/shift.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'css/stylesheet.css' %}">
<div class="card">
    <h3>Управление Сменами</h3>
    
    {% if current_shift %}
        <h5>Текущая смена: {{ current_shift.id }} (Открыта)</h5>
    {% else %}
        <h5>Нет открытой смены</h5>
    {% endif %}
    
    <form method="post" action="{% url 'orders:shift' %}" style="margin-bottom: 20px;">
        {% csrf_token %}
        <button type="submit" name="open" class="button button-green">Открыть смену</button>
        <button type="submit" name="close" class="button button-red">Закрыть смену</button>
    </form>
    
    <form method="get" action="{% url 'orders:shift' %}">
        <label for="shift_id">Выберите смену для подсчета выручки:</label>
        <select name="shift_id" id="shift_id" class="select">
            <option value="">-- Выберите смену --</option>
            {% for shift in shifts %}
                <option value="{{ shift.id }}">{{ shift }}</option>
            {% endfor %}
        </select>
        <button type="submit" name="calculate" class="button button-blue">Посчитать выручку</button>
    </form>
    
    {% if message %}
        <div class="alert-warning">
            {{ message }}
        </div>
    {% endif %}
</div>
{% endblock %}